services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 5s
      retries: 100
    env_file:
      - .env

  fastapi:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
