services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
  
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - .env
